swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Reporting!
host: magex9.github.io
basePath: /apis/restful
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /organizations:
    get:
      summary: List all organizations
      operationId: listOrganizations
      tags:
        - pets
      parameters:
        - name: displayName
          in: query
          description: Find an organization by its name
          required: false
          type: text
          format: string
      responses:
        "200":
          description: A paged array of organizations
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /organizations/{organizationId}:
    get:
      summary: Info for a specific organization
      operationId: showOrganizationById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Pet:
    type: "object"
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
