swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Reporting!
host: magex9.github.io
basePath: /apis/restful
consumes:
  - application/json
produces:
  - application/json
paths:
  /organizations:
    get:
      summary: List all organizations
      operationId: listOrganizations
      tags:
        - organizations
      parameters:
        - name: displayName
          in: query
          description: Find an organization by its name
          required: false
          type: string
      responses:
        "200":
          description: A paged array of organizations
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            type: array
            items:
              $ref: '#/definitions/Organization'
        default:
          description: System error
          schema:
            type: string
            example: '{error: Something went wrong...}'
    post:
      summary: Create an organization
      operationId: createOrganization
      tags:
        - organizations
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            type: string
            example: '{error: Something went wrong...}'
  /organizations/{organizationId}:
    get:
      summary: Info for a specific organization
      operationId: showOrganizationById
      tags:
        - organizations
      parameters:
        - name: organizationId
          in: path
          required: true
          description: The id of the organization to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Organization'
        default:
          description: unexpected error
          schema:
            type: string
            example: '{error: Something went wrong...}'
definitions:
  Organization:
    type: "object"
    required:
      - organizationId
      - status
      - displayName
    properties:
      organizationId:
        type: integer
        format: int64
      status:
        type: string
      displayName:
        type: string
      mainLocation:
        $ref: "#/definitions/Location"
  Location:
    type: "object"
    required: 
      - locationId
      - organizationId
      - status
      - locationReference
      - displayName
      - address
    properties:
      locationId:
        type: "string"
      organizationId:
        type: "string"
      status:
        type: "string"
      locationReference:
        type: "string"
      displayName:
        type: "string"
      address: 
        $ref: "#/definitions/MailingAddress"
  Country:
    type: "object"
    properties: 
      code: 
        type: "string"
      name:
        type: "string"
  Language:
    type: "object"
    properties: 
      code: 
        type: "string"
      name:
        type: "string"
  Salutation:
    type: "object"
    properties: 
      code: 
        type: "integer"
      name:
        type: "string"
  MailingAddress:
    type: "object"
    properties: 
      street:
        type: string
      city:
        type: string
      province:
        type: string
      country:
        $ref: "#/definitions/Country"
      postalCode:
        type: string
  Message:
    type: "object"
    required:
      - base
      - type
      - path
      - message
    properties:
      base:
        type: object
      type:
        type: string
      path:
        type: string
      message:
        type: string
